### ISSUE TITLE
Images in Toots not shown

### ISSUE THREAD

**Issue by jamfx** [nikosdion/fediverse#11]
### Steps to reproduce the issue
Install a blank new Joomla
Instal fedivers-Package
Insert Account which has Pictures in its stream.
See the Text from toot, but not the picture, If the toot is retootet in the stream from anyone else, but not from Original Poster. 
I used the account: https://troet.cafe/@doodlebrink for testing.

### Expected result
See the picture from the toot, too

### Actual result
Picture in the toot is not shown

### Troubleshooting already performed
Opened Github Issue :grimacing: 

### System information
Apache Server
* **Joomla! version**: 
* Joomla 4.3.2
* **Joomla! frontend template**: 
Cassiopeia (Default)
* **PHP version**: 
 8.0.28 
* **Browser (name and version)**: 
Firefox / Chrome

**Comment by nikosdion** [comment]
Images _are_ shown, except in reblogs (the Mastodon equivalent of a retweet). That's because they are not served from the server of the user whose toots you are listing. Since we make an API call to that server only, that server does not include these images as part of the ActivityPub response.

It's not a bug. It's how Mastodon implements the ActivityPub protocol.

**Comment by jamfx** [comment]
Hi Nicholas, thanks for clarification. Didn't knew that. Best regards and have a nice week. :blush:
